Job names should include the image type
YannickRe/azuredevops-buildagents pull request #82
Opened 2024-03-21 10:37 UTC by prashantchoudhary

https://github.com/YannickRe/azuredevops-buildagents/issues/81

2024-03-26 22:07 UTC, YannickRe requested changes
I have added comments, could you check them? Thanks for the work you did!

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-update-vmss.yml
> +    value: $[stageDependencies.${{ parameters.build_stage_job_name }}.outputs['setVars.ManagedImageNameOutput'] ]
Can we add the `.generate_image` back to this line? It's a bit cleaner so we aren't passing that from multiple places.

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-update-vmss.yml
> +  default: buildagent_template_vm.generate_image
Can we remove `.generate_image` here?

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-template.yml
> +          build_stage_job_name: buildagent_template_vm_${{ parameters.image_type }}.generate_image
Can we remove `.generate_image` here?

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-template.yml
> +          build_stage_job_name: buildagent_template_vm_${{ parameters.image_type }}.generate_image
Can we remove `.generate_image` here?

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-galleryvm.yml
> +  default: buildagent_template_vm.generate_image
Can we remove `.generate_image` here?

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-galleryvm.yml
> +    value: $[stageDependencies.${{parameters.build_stage_job_name}}.outputs['setVars.GalleryVmImageDefinition'] ]
Can we add the `.generate_image` back to this line? It's a bit cleaner so we aren't passing that from multiple places.

2024-03-26 22:07 UTC, YannickRe commented on buildagent-generation-galleryvm.yml
> +    value: $[stageDependencies.${{parameters.build_stage_job_name}}.outputs['setVars.ManagedImageNameOutput'] ]
Can we add the `.generate_image` back to this line? It's a bit cleaner so we aren't passing that from multiple places.

2024-12-27 20:12 UTC, YannickRe approved these changes

2024-12-27 20:12 UTC, merged

2024-12-27 20:18 UTC, YannickRe commented
I'm sorry, this took me a while as I had to make the requested changes myself.
Finally got around to it, and now I could merge.

2024-12-27 22:30 UTC, prashantchoudhary commented
Thanks a lot. I got busy with something else too and it just slipped my mind.